CREATE TABLE "USER" (
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  PASSWORD_SALT VARCHAR(255) NOT NULL,
  CONSTRAINT pk_username PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_ROLES (
  USERNAME VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  CONSTRAINT pk_user_roles PRIMARY KEY (USERNAME, ROLE),
  CONSTRAINT fk_username FOREIGN KEY (USERNAME) REFERENCES "USER"(USERNAME)
);

CREATE TABLE ROLES_PERMS (
  ROLE VARCHAR(255) NOT NULL,
  PERM VARCHAR(255) NOT NULL,
  CONSTRAINT pk_roles_perms PRIMARY KEY (ROLE),
  CONSTRAINT fk_roles FOREIGN KEY (ROLE) REFERENCES roles_perms(ROLE)
);